directories:
  output: release-desktop
  buildResources: build
appId: fr.warchess.desktop
productName: WarChess
files:
  - filter:
      - electron/**/*
      - package.json
      - build/icon.png
asar: true
win:
  target:
    - nsis
  icon: build/icon.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 31.7.7
